version: '3'
services:
  app:
    build: .
    image: cidadeinteligente_app
    ports:
      - "8080:8080"
    volumes:
      - ./target:/app/target
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
